/**
 * Created by tech on 1/31/2017.
 */
Ext.define('August.model.purchase.Order', {
    extend: 'August.model.Base',

    requires: [
        'Ext.data.identifier.Negative'
    ],
    
    fields: [
        { name: 'pono', type: 'int'},
        { name: 'orderDate', type: 'date', dateFormat: 'C' },
        { name: 'startDate', type: 'date', dateFormat: 'C' },
        { name: 'cancelDate', type: 'date', dateFormat: 'C' },
        { name: 'vendor', type: 'string'},
        { name: 'status', type: 'string'},
        { name: 'void', type: 'int'},
        { name: 'type', type: 'string'},
        { name: 'customer', type: 'string'},
        { name: 'onBoardDate', type: 'date', dateFormat: 'C'},
        { name: 'terms', type: 'string'},
        { name: 'shipvia', type: 'string'},
        { name: 'shipMark', type: 'string'},
        { name: 'LCNo', type: 'string'},
        { name: 'LCdate', type: 'date', dateFormat: 'C'},
        { name: 'BLNo', type: 'string'},
        { name: 'BLDate', type: 'date', dateFormat: 'C'},
        { name: 'memo', type: 'string'},
        { name: 'quota', type: 'number'},
        { name: 'duty', type: 'number'},
        { name: 'freight', type: 'number'},
        { name: 'createUser', type: 'string'},
        { name: 'createDate', type: 'date', dateFormat: 'C'},
        { name: 'updateUser', type: 'string'},
        { name: 'updateDate', type: 'date', dateFormat: 'C'},
        { name: 'userField1', type: 'string'},
        { name: 'userField1H', type: 'string'},
        { name: 'userField2', type: 'string'},
        { name: 'userField2H', type: 'string'},
        { name: 'userField3', type: 'string'},
        { name: 'userField3H', type: 'string'},
        { name: 'memoHouse', type: 'string'},        
        { name: 'SoNo', type: 'int'},
        { name: 'memocode', type: 'string'},
        { name: 'processType', type: 'string'},
        { name: 'cancelreason', type: 'string'},
        { name: 'cancelReasonDate', type: 'date', dateFormat: 'C' },
        { name: 'etaDate', type: 'date', dateFormat: 'C'},
        { name: 'shipto', type: 'string'},
        { name: 'paymentcode', type: 'string'},
        { name: 'division', type: 'string'},
        { name: 'warehouse', type: 'string'},
        { name: 'systemUpdated', type: 'string'},
        { name: 'controlNo', type: 'string'},
        { name: 'changeETA', type: 'number'},
        { name: 'originalETA', type: 'date', dateFormat: 'C' },        
        { name: 'cut_po', type: 'string'},
        { name: 'cust_po', type: 'string'},        
        { name: 'user1', type: 'string'},
        { name: 'user2', type: 'string'},
        { name: 'user3', type: 'string'},
        { name: 'user4', type: 'string'},
        { name: 'userf_date', type: 'date', dateFormat: 'C'},
        { name: 'Yield', type: 'number'},
        { name: 'cutWidth', type: 'number'},
        { name: 'self', type: 'string'},
        { name: 'contrast1', type: 'string'},
        { name: 'contrast2', type: 'string'},
        { name: 'contrast3', type: 'string'},
        { name: 'fusing', type: 'string'},
        { name: 'sendOut', type: 'string'},
        { name: 'shipdate', type: 'date', dateFormat: 'C'},
        { name: 'parent_po', type: 'int'},
        { name: 'house_only', type: 'string'},
        { name: 'ordertype', type: 'string'},
        { name: 'printcount', type: 'int'},
        { name: 'lastprintdate', type: 'date', dateFormat: 'C'},        
        { name: 'desc_material', type: 'string'},
        { name: 'desc_face', type: 'string'},
        { name: 'desc_origin', type: 'string'},
        { name: 'desc_cuttable', type: 'string'},
        { name: 'desc_cutydge', type: 'string'},
        { name: 'desc_markydge', type: 'string'},
        { name: 'desc_lining', type: 'string'},
        { name: 'desc_fusing', type: 'string'},
        { name: 'fabric_alloc_date', type: 'date', dateFormat: 'C'},
        { name: 'fabric_pull_date', type: 'date', dateFormat: 'C'},
        { name: 'fit_approv_date', type: 'date', dateFormat: 'C'},
        { name: 'marker_no', type: 'string'},
        { name: 'qb_batch_no', type: 'int'},
        { name: 'qb_batch_date', type: 'date', dateFormat: 'C'},
        { name: 'bulkpo', type: 'string'},
        { name: 'bulkpono', type: 'int'},
        { name: 'insurance_expdate', type: 'date', dateFormat: 'C'},
        { name: 'sr_group', type: 'string'},
        { name: 'custom_entry', type: 'string'},
        { name: 'apply_c_profile', type: 'string'},
        { name: 'vendor_shipto', type: 'string'},
        { name: 'sto_sono', type: 'int'},
        { name: 'sto_invoiceno', type: 'int'},
        { name: 'PriceTicket', type: 'string'},
        { name: 'sizeBreak', type: 'string'},
        { name: 'hangTag', type: 'string'},
        { name: 'bundle', type: 'string'},
        { name: 'polybag', type: 'string'},
        { name: 'fabricinfo', type: 'string'},
        { name: 'sentout', type: 'string'},
        { name: 'cuttablewidth', type: 'string'},
        { name: 'mainLabel', type: 'string'},
        { name: 'careLabel', type: 'string'},
        { name: 'fabricTesting', type: 'string'},
        { name: 'trimMemo', type: 'string'},
        { name: 'cutReleaseDate', type: 'date', dateFormat: 'C'},
        { name: 'cutFinishDate', type: 'date', dateFormat: 'C'},
        { name: 'sewingPickupDate', type: 'date', dateFormat: 'C'},
        { name: 'sewingDueDate', type: 'date', dateFormat: 'C'},
        { name: 'FOB', type: 'string'},                
        { name: 'sendout1', type: 'string'},
        { name: 'sendout2', type: 'string'},
        { name: 'sendout3', type: 'string'},
        { name: 'sendout4', type: 'string'},
        { name: 'sendout5', type: 'string'},                
        { name: 'fabricSt_no', type: 'string'},
        { name: 'widthShrinkage', type: 'string'},        
        { name: 'lengthShrinkage', type: 'string'},
        { name: 'sample', type: 'string'},
        { name: 'delivery_season', type: 'string'},
        { name: 'trade_term', type: 'string'},
        { name: 'user5', type: 'string' },
        { name: 'user6', type: 'string' },
        { name: 'user7', type: 'string' },
        { name: 'user8', type: 'string' },
        { name: 'user9', type: 'string' },
        { name: 'user10', type: 'string' },        
        { name: 'user11', type: 'string' },
        { name: 'user12', type: 'string' },
        { name: 'user13', type: 'string' },
        { name: 'user14', type: 'string' },
        { name: 'user15', type: 'string' },
        { name: 'user16', type: 'string' },
        { name: 'userdate', type: 'date', dateFormat: 'C' },
        { name: 'userdate1', type: 'date', dateFormat: 'C' },
        { name: 'userdate2', type: 'date', dateFormat: 'C' },
        { name: 'userdate3', type: 'date', dateFormat: 'C' },
        { name: 'Inhouse_memo1', type: 'string'},
        { name: 'Inhouse_memo2', type: 'string'},
        { name: 'user17', type: 'string'},
        { name: 'user18', type: 'string'},
        { name: 'currency', type: 'string'},
        { name: 'user19', type: 'string'},
        { name: 'user20', type: 'string'},        
        { name: 'user21', type: 'string'},        
        { name: 'user22', type: 'string'},        
        { name: 'user23', type: 'string'},        
        { name: 'user24', type: 'string'},        
        { name: 'user25', type: 'string'},        
        { name: 'user26', type: 'string'},        
        { name: 'user27', type: 'string'},        
        { name: 'user28', type: 'string'},        
        { name: 'user29', type: 'string'},        
        { name: 'user30', type: 'string'},        
        { name: 'styles', type: 'auto', defaultValue: [], persist: false },
        { name: 'totalUnits', type: 'int', defaultValue: 0, persist: false },
    ],

    idProperty: 'pono',
    identifier: 'negative',

    proxy: {
        type: 'rest',
        url: '/WebApp/api/PurchaseOrders',

        pageParam: '',
        startParam: '',
        limitParam: '',

        headers: {
            'Authorization' : 'Bearer ' + localStorage.getItem('access_token')
        },

        reader: {
            type: 'json',
            rootProperty: 'data'
        },

        writer: {
            type: 'json',
            // save nested (associated) data...
            allDataOptions: {
                persist: false,
                associated: true
            },
            partialDataOptions: {
                changes: false,
                critical: true,
                associated: true
            },
            //clientIdProperty: 'clientId',
            //writeAllFields: true,
            allowSingle: false // set false to send a single record in array
        },

        //extraParams: {},

        listeners: {                  
            exception: function (proxy, response, operation) {
                //console.log('Purchase.Order - Model', response, operation, August.app.accessToken);
                console.log('Purchase.Order - Model', response, operation);
            }
        }
    }
});
