Ext.define('August.model.sales.OrderItem', {
    extend: 'August.model.Base',

    requires: [
        'Ext.data.validator.Presence',
        'Ext.data.identifier.Negative'
    ],

    fields: [
        //{ name: 'orderno', type: 'int' },
        { name: 'orderType', type: 'string' },
        { name: 'division', type: 'string' },
        { name: 'orderdate', type: 'date', dateFormat: 'C' },
        { name: 'shipdate', type: 'date', dateFormat: 'C' },
        { name: 'canceldate', type: 'date', dateFormat: 'C' },
        { name: 'customer', type: 'string' },
        { name: 'email', type: 'string' },
        { name: 'store', type: 'string' },
        { name: 'shiptostore', type: 'string' },
        { name: 'dc', type: 'string' },
        { name: 'salesrep1', type: 'string' },
        { name: 'salesrep2', type: 'string' },
        { name: 'comrate1', type: 'number' },
        { name: 'comrate2', type: 'number' },
        { name: 'user1', type: 'string' },
        { name: 'user2', type: 'string' },
        { name: 'customerPo', type: 'string' },
        { name: 'terms', type: 'date', dateFormat: 'C' },
        { name: 'paymentcode', type: 'string' },
        { name: 'shipvia', type: 'string' },
        { name: 'discountrate', type: 'number' },
        { name: 'pricelevel', type: 'number' },
        { name: 'bulkorder', type: 'string' },
        { name: 'sod_id', type: 'int' },
        { name: 'sod_CancelDate', type: 'date', dateFormat: 'C' },
        { name: 'status', type: 'string' },
        { name: 'pono', type: 'string' },
        { name: 'soft_wip_alloc', type: 'string' },
        { name: 'line', type: 'int' },
        { name: 'style', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'wh', type: 'string' },
        { name: 'season', type: 'string' },
        { name: 'cancelReason', type: 'string' },
        { name: 'cancelReasondate', type: 'date', dateFormat: 'C' },
        { name: 'unit1', type: 'int' },
        { name: 'unit2', type: 'int' },
        { name: 'unit3', type: 'int' },
        { name: 'unit4', type: 'int' },
        { name: 'unit5', type: 'int' },
        { name: 'unit6', type: 'int' },
        { name: 'unit7', type: 'int' },
        { name: 'unit8', type: 'int' },
        { name: 'unit9', type: 'int' },
        { name: 'unit10', type: 'int' },
        { name: 'unit11', type: 'int' },
        { name: 'unit12', type: 'int' },
        { name: 'unit13', type: 'int' },
        { name: 'unit14', type: 'int' },
        { name: 'unit15', type: 'int' },
        { name: 'totalunit', type: 'int' },
        { name: 'price', type: 'number' },
        { name: 'extPrice', type: 'number' },
        { name: 'style_price', type: 'number' },
        { name: 'allo_qty', type: 'int' },
        { name: 'pick_qty', type: 'int' },
        { name: 'ship_qty', type: 'int' },
        { name: 'inv_qty', type: 'int' },
        { name: 'inv_Amt', type: 'number' },
        { name: 'cancel_qty', type: 'number' },
        { name: 'Cancel_amt', type: 'number' },
        { name: 'Bal_unit1', type: 'int' },
        { name: 'Bal_unit2', type: 'int' },
        { name: 'Bal_unit3', type: 'int' },
        { name: 'Bal_unit4', type: 'int' },
        { name: 'Bal_unit5', type: 'int' },
        { name: 'Bal_unit6', type: 'int' },
        { name: 'Bal_unit7', type: 'int' },
        { name: 'Bal_unit8', type: 'int' },
        { name: 'Bal_unit9', type: 'int' },
        { name: 'Bal_unit10', type: 'int' },
        { name: 'Bal_unit11', type: 'int' },
        { name: 'Bal_unit12', type: 'int' },
        { name: 'Bal_unit13', type: 'int' },
        { name: 'Bal_unit14', type: 'int' },
        { name: 'Bal_unit15', type: 'int' },
        { name: 'cost', type: 'number' },
        { name: 'avgcost', type: 'number' },
        { name: 'grp', type: 'number' },
        { name: 'category', type: 'string' },
        { name: 'Sizecat', type: 'string' },
        { name: 'descript', type: 'string' },
        { name: 'ohs', type: 'int' },
        { name: 'orders', type: 'int' },
        { name: 'pos', type: 'string' },
        { name: 'ats', type: 'number' },
        { name: 'ots', type: 'number' },
        { name: 'Size1', type: 'string' },
        { name: 'Size2', type: 'string' },
        { name: 'Size3', type: 'string' },
        { name: 'Size4', type: 'string' },
        { name: 'Size5', type: 'string' },
        { name: 'Size6', type: 'string' },
        { name: 'Size7', type: 'string' },
        { name: 'Size8', type: 'string' },
        { name: 'Size9', type: 'string' },
        { name: 'Size10', type: 'string' },
        { name: 'Size11', type: 'string' },
        { name: 'Size12', type: 'string' },
        { name: 'Size13', type: 'string' },
        { name: 'Size14', type: 'string' },
        { name: 'Size15', type: 'string' },
        { name: 'cust_name', type: 'string' },
        { name: 'customerType', type: 'string' },
        { name: 'contact', type: 'string' },
        { name: 'phone1', type: 'string' },
        { name: 'address1', type: 'string' },
        { name: 'city', type: 'string' },
        { name: 'state', type: 'string' },
        { name: 'zip', type: 'string' },
        { name: 'designer', type: 'string' },
        { name: 'vendor1', type: 'string' },
        { name: 'vendor2', type: 'string' },
        { name: 'vendor3', type: 'string' },
        { name: 'processtype', type: 'string' },
        { name: 'st_user1', type: 'string' },
        { name: 'st_user4', type: 'string' },
        { name: 'territory', type: 'string' },
        { name: 'print_count', type: 'int' },
        { name: 'UpdateUser', type: 'string' },
        { name: 'updatetime', type: 'date', dateFormat: 'C' },
        { name: 'st_division', type: 'string' },
        { name: 'userf_date', type: 'date', dateFormat: 'C' },
        { name: 'binlocation', type: 'string' },
        { name: 'net_so', type: 'number' },
        { name: 'net_so_amt', type: 'number' },
        { name: 'Acutal_cost', type: 'number' },
        { name: 'Process_type', type: 'string' },
        { name: 'PO_Qty', type: 'int' },
        { name: 'PO_Price', type: 'number' },
        { name: 'PO_ExtPrice', type: 'number' },
        { name: 'PO_RcvQty', type: 'int' },
        { name: 'PO_Vendor', type: 'string' },
        { name: 'price1', type: 'number' },
        { name: 'available_date', type: 'date', dateFormat: 'C' },
        { name: 'factor_ref', type: 'string' },
        { name: 'status_style', type: 'string' },
        { name: 'tradeshow', type: 'string' },
        { name: 'memo', type: 'string' },
        { name: 'subcategory', type: 'string' },
        { name: 'avail_alloc', type: 'string' },
        { name: 'style_id', type: 'int' },
        { name: 'invoiceno', type: 'int' },
        { name: 'cmno', type: 'int' },
        { name: 'invoicedate', type: 'date', dateFormat: 'C' },
        { name: 'invUnit1', type: 'int' },
        { name: 'invUnit2', type: 'int' },
        { name: 'invUnit3', type: 'int' },
        { name: 'invUnit4', type: 'int' },
        { name: 'invUnit5', type: 'int' },
        { name: 'invUnit6', type: 'int' },
        { name: 'invUnit7', type: 'int' },
        { name: 'invUnit8', type: 'int' },
        { name: 'invUnit9', type: 'int' },
        { name: 'invUnit10', type: 'int' },
        { name: 'invUnit11', type: 'int' },
        { name: 'invUnit12', type: 'int' },
        { name: 'invUnit13', type: 'int' },
        { name: 'invUnit14', type: 'int' },
        { name: 'invUnit15', type: 'int' },
        { name: 'invTotal', type: 'number' },
        { name: 'invPrice', type: 'number' },
        { name: 'invExtprice', type: 'number' },
        { name: 'c_user3', type: 'string' },
        { name: 'not_allocate', type: 'boolean' },
        { name: 'exclude_freight', type: 'string' },
        { name: 'create_date', type: 'date', dateFormat: 'C' },
        { name: 'create_user', type: 'string' },
        { name: 'msrp', type: 'number' },
        { name: 'price2', type: 'number' },
        { name: 'price3', type: 'number' },
        { name: 'price4', type: 'number' },
        { name: 'price5', type: 'number' },
        { name: 'inv_status', type: 'string' },
        { name: 'inv_balance', type: 'int' },
        { name: 'startselldate', type: 'date', dateFormat: 'C' },
        { name: 'user3', type: 'string' },            
        {
            //
            //     When associate models,
            //     model name with Id prefixed.
            //     ex. pihId
            //    or using field...
            //
            name: 'orderno',
            //mapping: 'orderNo', persist: false,
            reference: {
                parent: 'sales.Order',

                field: 'orderno',
                inverse: 'salesorderitems'
            }
        }         
    ],

    idProperty: 'sod_id',
    identifier: 'negative',

    proxy: {
        type: 'rest',
        url: '/WebApp/api/SalesOrderItems',

        pageParam: '',
        startParam: '',
        limitParam: '',

        headers: {
            'Authorization' : 'Bearer ' + localStorage.getItem('access_token')
        },

        reader: {
            type: 'json',
            rootProperty: 'data'
        },

        writer: {
            type: 'json',
            //clientIdProperty: 'clientId',
            //writeAllFields: true,
            allowSingle: false // set false to send a single record in array
        },

        extraParams: {},

        listeners: {            
            exception: function (proxy, response, operation) {
                console.log('OrderItem - Model', response, operation);
            }
        }
    }
});