Ext.define('August.model.shopify.AmazonTemplate', {
    extend: 'August.model.Base',

    requires: [
        'Ext.data.validator.Presence'
    ],    

    fields: [       
        { name: 'product_type', type: 'string' },
        { name: 'seller_sku', type: 'string' },
        { name: 'brand_name', type: 'string' },
        { name: 'product_name', type: 'string' },
        { name: 'product_id', type: 'string' },
        { name: 'product_id_type', type: 'string' },
        { name: 'item_type_keyword', type: 'string' },
        { name: 'outer_material_type', type: 'string' },
        { name: 'outer_material_type1', type: 'string' },
        { name: 'outer_material_type2', type: 'string' },
        { name: 'outer_material_type3', type: 'string' },
        { name: 'outer_material_type4', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'color_map', type: 'string' },
        { name: 'department', type: 'string' },
        { name: 'neckstyle', type: 'string' },
        { name: 'pattern_style', type: 'string' },
        { name: 'size', type: 'string' },
        { name: 'style', type: 'string' },
        { name: 'occasion_lifestyle', type: 'string' },
        { name: 'product_lifecycle_supply_type', type: 'string' },
        { name: 'size_map', type: 'string' },
        { name: 'item_length', type: 'string' },
        { name: 'fabric_type', type: 'string' },
        { name: 'material_fabric_regulations', type: 'string' },
        { name: 'material_fabric_regulations1', type: 'string' },
        { name: 'material_fabric_regulations2', type: 'string' },
        { name: 'your_price', type: 'string' },
        { name: 'quantity', type: 'string' },
        { name: 'main_image_url', type: 'string' },
        { name: 'target_gender', type: 'string' },
        { name: 'age_range_description', type: 'string' },
        { name: 'apparel_size_system', type: 'string' },
        { name: 'apparel_size_class', type: 'string' },
        { name: 'apparel_size_value', type: 'string' },
        { name: 'apparel_size_to_range', type: 'string' },
        { name: 'apparel_size_body_type', type: 'string' },
        { name: 'apparel_size_height_type', type: 'string' },
        { name: 'other_image_url1', type: 'string' },
        { name: 'other_image_url2', type: 'string' },
        { name: 'other_image_url3', type: 'string' },
        { name: 'other_image_url4', type: 'string' },
        { name: 'other_image_url5', type: 'string' },
        { name: 'other_image_url6', type: 'string' },
        { name: 'other_image_url7', type: 'string' },
        { name: 'other_image_url8', type: 'string' },
        { name: 'parentage', type: 'string' },
        { name: 'parent_sku', type: 'string' },
        { name: 'relationship_type', type: 'string' },
        { name: 'variation_theme', type: 'string' },
        { name: 'package_level', type: 'string' },
        { name: 'package_contains_quantity', type: 'string' },
        { name: 'package_contains_identifier', type: 'string' },
        { name: 'update_delete', type: 'string' },
        { name: 'product_description', type: 'string' },
        { name: 'closure_type', type: 'string' },
        { name: 'style_number', type: 'string' },
        { name: 'inner_material_type', type: 'string' },
        { name: 'manufacturer_part_number', type: 'string' },
        { name: 'manufacturer', type: 'string' },
        { name: 'key_product_features', type: 'string' },
        { name: 'key_product_features1', type: 'string' },
        { name: 'key_product_features2', type: 'string' },
        { name: 'key_product_features3', type: 'string' },
        { name: 'key_product_features4', type: 'string' },
        { name: 'search_terms', type: 'string' },
        { name: 'belt_style', type: 'string' },
        { name: 'collar_type', type: 'string' },
        { name: 'control_type', type: 'string' },
        { name: 'fit_type', type: 'string' },
        { name: 'country_region_as_labeled', type: 'string' },
        { name: 'fur_description', type: 'string' },
        { name: 'pocket_description', type: 'string' },
        { name: 'special_size_type', type: 'string' },
        { name: 'additional_features', type: 'string' },
        { name: 'additional_features1', type: 'string' },
        { name: 'additional_features2', type: 'string' },
        { name: 'additional_features3', type: 'string' },
        { name: 'additional_features4', type: 'string' },
        { name: 'theme', type: 'string' },
        { name: 'top_style', type: 'string' },
        { name: 'water_resistance_level', type: 'string' },
        { name: 'is_autographed', type: 'string' },
        { name: 'athlete', type: 'string' },
        { name: 'team_name', type: 'string' },
        { name: 'material_type', type: 'string' },
        { name: 'weave_type', type: 'string' },
        { name: 'league_name', type: 'string' },
        { name: 'shaft_style_type', type: 'string' },
        { name: 'bottom_style', type: 'string' },
        { name: 'fabric_wash', type: 'string' },
        { name: 'sleeve_type', type: 'string' },
        { name: 'underwire_type', type: 'string' },
        { name: 'duration_unit', type: 'string' },
        { name: 'legal_compliance_certification_certifying_authority_name', type: 'string' },
        { name: 'duration', type: 'string' },
        { name: 'legal_compliance_certification_geographic_jurisdiction', type: 'string' },
        { name: 'shipping_weight', type: 'string' },
        { name: 'website_shipping_weight_unit_of_measure', type: 'string' },
        { name: 'chest_size', type: 'string' },
        { name: 'chest_size_unit_of_measure', type: 'string' },
        { name: 'band_size_numeric', type: 'string' },
        { name: 'band_size_num_unit_of_measure', type: 'string' },
        { name: 'cup_size', type: 'string' },
        { name: 'neck_size', type: 'string' },
        { name: 'neck_size_unit_of_measure', type: 'string' },
        { name: 'sleevelength', type: 'string' },
        { name: 'sleeve_length_unit_of_measure', type: 'string' },
        { name: 'waistsize', type: 'string' },
        { name: 'waist_size_unit_of_measure', type: 'string' },
        { name: 'item_length1', type: 'string' },
        { name: 'item_width', type: 'string' },
        { name: 'item_height', type: 'string' },
        { name: 'item_dimensions_unit_of_measure', type: 'string' },
        { name: 'fulfillment_center_id', type: 'string' },
        { name: 'package_height', type: 'string' },
        { name: 'package_width', type: 'string' },
        { name: 'package_length', type: 'string' },
        { name: 'package_weight', type: 'string' },
        { name: 'package_weight_unit_of_measure', type: 'string' },
        { name: 'package_dimensions_unit_of_measure', type: 'string' },
        { name: 'compliance_regulation_type', type: 'string' },
        { name: 'compliance_regulation_type1', type: 'string' },
        { name: 'compliance_regulation_type2', type: 'string' },
        { name: 'compliance_regulation_type3', type: 'string' },
        { name: 'compliance_regulation_type4', type: 'string' },
        { name: 'regulatory_identification', type: 'string' },
        { name: 'regulatory_identification1', type: 'string' },
        { name: 'regulatory_identification2', type: 'string' },
        { name: 'regulatory_identification3', type: 'string' },
        { name: 'regulatory_identification4', type: 'string' },
        { name: 'cpsia_warning', type: 'string' },
        { name: 'cpsia_warning_description', type: 'string' },
        { name: 'import_designation', type: 'string' },
        { name: 'item_weight_unit_of_measure', type: 'string' },
        { name: 'item_weight', type: 'string' },
        { name: 'country_region_of_origin', type: 'string' },
        { name: 'is_this_product_a_battery_or_does_it_utilize_batteries?', type: 'string' },
        { name: 'batteries_are_included', type: 'string' },
        { name: 'battery_composition', type: 'string' },
        { name: 'battery_type_size', type: 'string' },
        { name: 'battery_type_size1', type: 'string' },
        { name: 'battery_type_size2', type: 'string' },
        { name: 'number_of_batteries', type: 'string' },
        { name: 'number_of_batteries1', type: 'string' },
        { name: 'number_of_batteries2', type: 'string' },
        { name: 'battery_weight_grams', type: 'string' },
        { name: 'battery_weight_unit_of_measure', type: 'string' },
        { name: 'number_of_lithium_metal_cells', type: 'string' },
        { name: 'number_of_lithium_ion_cells', type: 'string' },
        { name: 'lithium_battery_packaging', type: 'string' },
        { name: 'watt_hours_per_battery', type: 'string' },
        { name: 'lithium_battery_energy_content_unit_of_measure', type: 'string' },
        { name: 'lithium_content_grams', type: 'string' },
        { name: 'lithium_battery_weight_unit_of_measure', type: 'string' },
        { name: 'applicable_dangerous_goods_regulations', type: 'string' },
        { name: 'applicable_dangerous_goods_regulations1', type: 'string' },
        { name: 'applicable_dangerous_goods_regulations2', type: 'string' },
        { name: 'applicable_dangerous_goods_regulations3', type: 'string' },
        { name: 'applicable_dangerous_goods_regulations4', type: 'string' },
        { name: 'un_number', type: 'string' },
        { name: 'safety_data_sheet_sds_url', type: 'string' },
        { name: 'volume', type: 'string' },
        { name: 'item_volume_unit_of_measure', type: 'string' },
        { name: 'legal_compliance_certification_expiration_date', type: 'string' },
        { name: 'regulatory_organization_name', type: 'string' },
        { name: 'compliance_certification_status', type: 'string' },
        { name: 'flash_point', type: 'string' },
        { name: 'legal_compliance_certification_date_of_issue', type: 'string' },
        { name: 'legal_compliance_certification_metadata', type: 'string' },
        { name: 'legal_compliance_certification', type: 'string' },
        { name: 'categorization_ghs_pictograms', type: 'string' },
        { name: 'categorization_ghs_pictograms1', type: 'string' },
        { name: 'categorization_ghs_pictograms2', type: 'string' },
        { name: 'california_proposition_65_warning_type', type: 'string' },
        { name: 'california_proposition_65_chemical_names', type: 'string' },
        { name: 'additional_chemical_name1', type: 'string' },
        { name: 'additional_chemical_name2', type: 'string' },
        { name: 'additional_chemical_name3', type: 'string' },
        { name: 'additional_chemical_name4', type: 'string' },
        { name: 'pesticide_marking', type: 'string' },
        { name: 'pesticide_marking1', type: 'string' },
        { name: 'pesticide_marking2', type: 'string' },
        { name: 'pesticide_registration_status', type: 'string' },
        { name: 'pesticide_registration_status1', type: 'string' },
        { name: 'pesticide_registration_status2', type: 'string' },
        { name: 'pesticide_certification_number', type: 'string' },
        { name: 'pesticide_certification_number1', type: 'string' },
        { name: 'pesticide_certification_number2', type: 'string' },
        { name: 'radio_frequency_emission_&_authorization_status', type: 'string' },
        { name: 'sdoc_contact_email_address', type: 'string' },
        { name: 'sdoc_contact_us_phone_number', type: 'string' },
        { name: 'sdoc_contact_name', type: 'string' },
        { name: 'fcc_id', type: 'string' },
        { name: 'sdoc_contact_us_mailing_address', type: 'string' },
        { name: 'list_price', type: 'string' },
        { name: 'product_tax_code', type: 'string' },
        { name: 'handling_time', type: 'string' },
        { name: 'launch_date', type: 'string' },
        { name: 'release_date', type: 'string' },
        { name: 'restock_date', type: 'string' },
        { name: 'sale_price', type: 'string' },
        { name: 'sale_start_date', type: 'string' },
        { name: 'sale_end_date', type: 'string' },
        { name: 'offer_end_date', type: 'string' },
        { name: 'max_aggregate_ship_quantity', type: 'string' },
        { name: 'package_quantity', type: 'string' },
        { name: 'number_of_items', type: 'string' },
        { name: 'offering_can_be_gift_messaged', type: 'string' },
        { name: 'is_gift_wrap_available', type: 'string' },
        { name: 'is_discontinued_by_manufacturer', type: 'string' },
        { name: 'max_order_quantity', type: 'string' },
        { name: 'shipping_template', type: 'string' },
        { name: 'offer_start_date', type: 'string' },
        { name: 'business_price', type: 'string' },
        { name: 'quantity_price_type', type: 'string' },
        { name: 'quantity_lower_bound_1', type: 'string' },
        { name: 'quantity_price_1', type: 'string' },
        { name: 'quantity_lower_bound_2', type: 'string' },
        { name: 'quantity_price_2', type: 'string' },
        { name: 'quantity_lower_bound_3', type: 'string' },
        { name: 'quantity_price_3', type: 'string' },
        { name: 'quantity_lower_bound_4', type: 'string' },
        { name: 'quantity_price_4', type: 'string' },
        { name: 'quantity_lower_bound_5', type: 'string' },
        { name: 'quantity_price_5', type: 'string' },
        { name: 'progressive_discount_type', type: 'string' },
        { name: 'progressive_discount_lower_bound_1', type: 'string' },
        { name: 'progressive_discount_value_1', type: 'string' },
        { name: 'progressive_discount_lower_bound_2', type: 'string' },
        { name: 'progressive_discount_value_2', type: 'string' },
        { name: 'progressive_discount_lower_bound_3', type: 'string' },
        { name: 'progressive_discount_value_3', type: 'string' },
        { name: 'national_stock_number', type: 'string' },
        { name: 'united_nations_standard_products_and_services_code', type: 'string' },
        { name: 'pricing_action', type: 'string' }    
    ],

    //identifier: 'negative',

    validators: {
        //style: 'presence',
        //color: 'presence'        
    },

    proxy: {
        type: 'rest',
        
        url: '/WebApp/api/ProductTemplates',        
        
        actionMethods: {
            read: 'POST'
        },

        pageParam: '',
        startParam: '',
        limitParam: '',

        headers: {
            'Authorization' : 'Bearer ' + localStorage.getItem('access_token')
        },

        reader: {
            type: 'json',
            rootProperty: 'data'
        },

        writer: {
            type: 'json',
            //clientIdProperty: 'clientId',
            //writeAllFields: true,
            allowSingle: false // set false to send a single record in array
        },

        //extraParams: {},

        listeners: {
            exception: function (proxy, response, operation) {
                console.log(response, operation);
            }
        }
    }
});